# Generated by Django 6.1.2 on 2026-10-08 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="ФИО")),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(max_length=150, verbose_name="Тема сообщения"),
                ),
                ("text", models.TextField(verbose_name="Текст сообщения")),
            ],
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sending_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "создана"),
                            ("sent", "отправлена"),
                            ("completed", "завершена"),
                            ("canceled", "отменена"),
                        ],
                        default="created",
                        max_length=50,
                        verbose_name="Состояние рассылки",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("once a day", "раз в день"),
                            ("once a week", "раз в неделю"),
                            ("once a month", "раз в месяц"),
                        ],
                        default="once a day",
                        max_length=20,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "client",
                    models.ManyToManyField(
                        to="mailing.client", verbose_name="Получатель"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mailing.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MailingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата последней попытки"
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "answer",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ответ почтового сервера"
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
        ),
    ]
