# Generated by Django 6.1.2 on 2026-10-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="client",
            new_name="recipients",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="sending_date",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="status",
        ),
        migrations.AddField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время окончания"
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время начала"
            ),
        ),
    ]
