# Generated by Django 6.1.2 on 2026-10-09 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0002_rename_client_mailing_recipients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата и время окончания"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата и время начала"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата последней попытки",
            ),
            preserve_default=False,
        ),
    ]
