# Generated by Django 6.1.2 on 2026-10-09 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0003_alter_mailing_end_time_alter_mailing_start_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailinglog",
            old_name="answer",
            new_name="server_response",
        ),
        migrations.RemoveField(
            model_name="mailinglog",
            name="date",
        ),
        migrations.AddField(
            model_name="mailinglog",
            name="attempt_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата и время последней попытки",
            ),
            preserve_default=False,
        ),
    ]
